routes:
    - route: "^.+\\.(js|css|svg|ttf|woff|eot|gif|pdf|jpeg|png|jpg)$"
      #  cache static assets for 20 years
      headers:
         Cache-Control: "max-age=630720000, no-transform, public"
      gzip: true
    - route: "^.+\\.(js|css)$"
      #  cache style, code for 1 hour
      headers:
         Cache-Control: "max-age=3600, no-transform, public"
      gzip: true
    - route: "^.+\\.(js|css|json)$"
      #  cache JSON (for JSON-feed) for 20m
      headers:
         Cache-Control: "max-age=1200, no-transform, public"
      gzip: true
