baseURL = "https://serialized.net"
languageCode = "en-us"
title = "Ongoing Fascination Burnout"
theme = "serialized"
googleAnalytics = "UA-15368739-1"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
enableEmoji = "true"
enableRobotsTXT = true
pygmentsCodeFences = true
pygmentsUseClasses=true

[markup.goldmark.renderer]
unsafe = true

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3

[outputs]
  home = [ "HTML", "JSON", "RSS"]

[params]
  name = "Joshua Barratt"
  author = "Joshua Barratt"
  author_url = "https://serialized.net"
  description = "Josh Barratt's personal site, writing about tech, food, and everything else fascinating to me"

[author]
    name = "Joshua Barratt"
    url = "https://serialized.net"
    email = "jbarratt@serialized.net"

[permalinks]
  post = "/:year/:month/:slug/"

#[mediaTypes]
#  [mediaTypes."image/svg+xml"]
#    suffixes = ["svg"]

[[menu.main]]
    name = "Posts"
    # pre = "<i class='fa fa-road'></i>"
    weight = -110
    url = "/post/"

[[menu.main]]
    name = "About"
    # pre = "<i class='fa fa-heart'></i>"
    weight = -100
    identifier = "about"
    url = "/about/"

[[deployment.targets]]

name = "serialized"
URL="s3://serialized?region=us-west-2"
cloudFrontDistributionID = "E374LZZY9EPZLY"

[[deployment.matchers]]

pattern = "^.+\\.(js|css|svg|ttf|woff|eot|gif|pdf|jpeg|png|jpg)$"
cacheControl = "max-age=630720000, no-transform, public"
gzip = false

[[deployment.matchers]]

pattern = "^.+\\.(js|css|json)$"
cacheControl = "max-age=1200, no-transform, public"
gzip = false
