baseURL = "https://serialized.net"
languageCode = "en-us"
title = "serialized.net"
theme = "serialized"
googleAnalytics = "UA-15368739-1"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
enableEmoji = "true"
enableRobotsTXT = true
pygmentsCodeFences = true
pygmentsUseClasses=true

[outputs]
  home = [ "HTML", "JSON", "RSS"]

[params]
  name = "Joshua Barratt"
  author = "Joshua Barratt"
  author_url = "https://serialized.net"
  description = "A study in fascination burnout"

[author]
    name = "Joshua Barratt"
    email = "jbarratt@serialized.net"

[permalinks]
  post = "/:year/:month/:slug/"

[mediaTypes]
  [mediaTypes."image/svg+xml"]
    suffixes = ["svg"]

[[menu.main]]
    name = "Posts"
    # pre = "<i class='fa fa-road'></i>"
    weight = -110
    url = "/post/"

[[menu.main]]
    name = "About"
    # pre = "<i class='fa fa-heart'></i>"
    weight = -100
    identifier = "about"
    url = "/about/"
